### ISSUE TITLE
Use system environment variables

### ISSUE THREAD

**Issue by pezholio** [Teradata/jaqy#18]
Hi,

I'm currently using jaqy to run in a Docker container for debugging purposes. Rather than having to extract the database connection details manually, I'd like to get them from the system env vars automatically. Something like:

```
.open -u ${USERNAME} -p ${PASSWORD} postgresql://${DB_HOST}/${DB_NAME}
```

However, this doesn't seem to work. Another approach I've tried is generating a script to pipe into jaqy like so:

```
$ echo """
.classpath postgresql postgresql-42.5.1.jar
.open -u ${USERNAME} -p ${PASSWORD} postgresql://${DB_HOST}/${DB_NAME}
""" > jaqyinit

$ java -jar jaqy-1.2.0.jar < jaqyinit
```

But the script exits as soon as it runs

Is there another approach I could try?

**Comment by coconut2015** [comment]
1. You can write JavaScript to pickup the environmental variables.
2. You can use command line.  Use `;` to separate jaqy command.
```bash
java -jar jaqy-1.2.0.jar .classpath postgresql postgresql-42.5.1.jar \; .open -u ${USERNAME} -p ${PASSWORD} postgresql://${DB_HOST}/${DB_NAME}
```

**Comment by pezholio** [comment]
Thanks for the quick response, however that gives me an error:

```
Unrecognized option: -u
```

I've tried a few other ways round (enclosing in quotes etc), but nothing seems to work. Any other ideas? Thanks!

**Comment by coconut2015** [comment]
My bad.  Because jaqy had command line options as well, so it is necessary to add `--` to disable options parsing after certain arguments.  See the example below.
```bash
java -jar jaqy-1.2.0.jar -- .classpath postgresql postgresql-42.5.1.jar \; .open -u ${USERNAME} -p ${PASSWORD} postgresql://${DB_HOST}/${DB_NAME}
```

**Comment by pezholio** [comment]
Amazing. That's got it - thanks!

**Comment by coconut2015** [comment]
I noticed that I did not have any documentations on jaqy command line options.

The documentation is now updated.  There should be some simple / complicated examples that you may use.

**Comment by pezholio** [comment]
Brilliant - thanks!
