### ISSUE TITLE
where should we find the drivers?

### ISSUE THREAD

**Issue by abubelinha** [Teradata/jaqy#3]
Firstly I ran this command:
```
.protocol
Protocol   Driver
---------- --------------------------------------------
mysql      com.mysql.jdbc.Driver
oracle     oracle.jdbc.driver.OracleDriver
postgresql org.postgresql.Driver
sqlite     org.sqlite.JDBC
sqlserver  com.microsoft.sqlserver.jdbc.SQLServerDriver
teradata   com.teradata.jdbc.TeraDriver
```
Where should we look for those drivers?
This is not explained in the docs.
I want to connect to a postgresql server, so I ran this command and got an error:

```
.open -u myusername -p mypassword postgresql://127.0.0.1
-- error: driver not found: org.postgresql.Driver
```

**Comment by coconut2015** [comment]
You need to download from the appropriate driver from your database vendor / provider's website.

**Comment by abubelinha** [comment]
> You need to download from the appropriate driver from your database vendor / provider's website.

I want to connect a Postresql server 12.
I googled org.postgresql.Driver and landed in this page:
https://jdbc.postgresql.org/download.html

But there are a bunch of choices and I have no idea:
JDBC 1	JDBC 2	JDBC 2 EE	JDBC 3	JDBC 4.0	JDBC 4.1	JDBC 4.2
... and so many versions of each one.

Should I get the most recent one?
Where should I save it once downloaded?  
Same folder as your jaqy-1.1.0.jar file?

I think this info would be useful in the [instructions page](https://teradata.github.io/jaqy/start.html).
Thanks in advance.
