### ISSUE TITLE
Some roadmap?

### ISSUE THREAD

**Issue by kination** [Teradata/jaqy#9]
Hello~ this is just a question.
Is there some roadmap(or features to be done) of the project you're thinking of?

**Comment by coconut2015** [comment]
I am currently working 1.20.  Hopefully in couple weeks.  It has Excel export / import support.  Also working on improving CSV, AVRO and JSON handling.

Other than that, no specific roadmaps.  After all, this is a solo project.  I have a number of personal projects on my plate.
